[Add] データベース構造
tsukuba-shinkan/shinkan-web-api pull request #2
Opened 2020-09-25 13:47 UTC by asagatto777

#1 決定のデータベース構造をSQLファイルにしました。
なお、`organization_contents_image`において`imege_id`カラムを追加し、`image_id`を主キーとしました。

2020-09-25 15:51 UTC, mkobayashime requested changes

2020-09-25 15:51 UTC, mkobayashime commented on database.sql
> +  `updated_at` timestamp NOT NULL DEFAULT current_timestamp()
`ON UPDATE current_timestamp()`抜けてるような気がします

2020-09-25 15:54 UTC, mkobayashime requested changes

2020-09-25 15:54 UTC, mkobayashime commented on database.sql
> +  `mail` varchar(255) NOT NULL,
`mail`->`email`

2020-09-25 15:55 UTC, asagatto777 commented on database.sql
> +  `updated_at` timestamp NOT NULL DEFAULT current_timestamp()
ありがとうございます！！！！！

2020-09-25 15:56 UTC, asagatto777 commented on database.sql
> +  `mail` varchar(255) NOT NULL,
ありがとうございます！！！

2020-09-26 09:41 UTC, asagatto777 commented
@nandenjin @yuki-js 
レビューいただけるとありがたいです～～

2020-09-27 09:13 UTC, nandenjin approved these changes

2020-09-27 09:13 UTC, nandenjin commented on database.sql
> +/*!40101 SET NAMES utf8mb4 */;
このへんって何らかの意味あるんかな、ないのなら消しときたいです 何の挙動を引き起こすかわからない……

2020-09-27 09:13 UTC, nandenjin commented on database.sql
> +/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
ここも

2020-09-27 09:25 UTC, nandenjin requested changes
`user_id`の桁数だけ変えたいです、そのほかは要検討なきもち

2020-09-27 09:25 UTC, nandenjin commented on database.sql
> +  `activity_type` varchar(8) NOT NULL,
typeって`varchar`なんですか？`enum`みたく制約かけるのかと思ってました、意見聞きたいです

2020-09-27 09:25 UTC, nandenjin commented on database.sql
> +  `image_type` varchar(32) NOT NULL,
この`type`も制約かけた方がいい気がしますがどうでしょう？

2020-09-27 09:25 UTC, nandenjin commented on database.sql
> +  `user_id` varchar(36) NOT NULL,
[Firebaseのドキュメント](https://firebase.google.com/docs/auth/admin/manage-users#create_a_user)で`uid`が128まで許容することになってるのでそれに合わせたいです🙋‍♂️

> The uid to assign to the newly created user. Must be a string between 1 and 128 characters long, inclusive. If not provided, a random uid will be automatically generated.

2020-09-27 09:25 UTC, nandenjin commented on database.sql
> +--
`organization`のインクリメントがなさそうですが、UI作らず手動でID決めて入れる感じですか？🤔

2021-01-04 18:00 UTC, AsagaKosho commented on database.sql
> +--
すでに団体のリストはある＆旧システムでIDは決められているので必要ないとの判断でしたが、手動で値を入れることも可のようなので追加しますね

2021-01-04 18:40 UTC, AsagaKosho commented on database.sql
> +  `activity_type` varchar(8) NOT NULL,
制約かけますね

2021-01-04 18:40 UTC, AsagaKosho commented on database.sql
> +  `image_type` varchar(32) NOT NULL,
こちらも制約かけます

2021-01-05 07:19 UTC, AsagaKosho commented on database.sql
> +/*!40101 SET NAMES utf8mb4 */;
https://teratail.com/questions/69819
参考程度ですが、バージョン指定など意味のあるものであるようです。

2021-03-02 13:09 UTC, AsagaKosho commented
@nandenjin @mkobayashime 
#4 と共にご確認お願いしたいです!

2021-03-02 13:23 UTC, mkobayashime commented
@AsagaKosho 
大変申し訳ないんですが、コントリビュートする時間が取れそうにないため、レビューなどはパスしていただけると助かります…
この PR ブロックしてたらすいません…

2021-03-02 13:24 UTC, AsagaKosho commented
@mkobayashime 承知しました！

2021-03-03 04:48 UTC, nandenjin approved these changes

2021-03-05 10:04 UTC, merged